.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DETROIT\-MINITEST" "5" "October 2011" "" ""
.
.SH "NAME"
\fBdetroit\-minitest\fR \- ruby minitest\-based test via detroit
.
.SH "DESCRIPTION"
MiniTest test runner tool can run your Ruby tests during the standard test phase\.
.
.SH "OPTIONS"
The following options can be used in the Detroit assembly file for defining a dnote service\.
.
.IP "\(bu" 4
\fBtests\fR \- Test files to include\.
.
.IP "\(bu" 4
\fBexclude\fR \- Files or globs to exclude\.
.
.IP "\(bu" 4
\fBignore\fR \- Files to ignore by matching filename\.
.
.IP "\(bu" 4
\fBloadpath\fR \- Directories to add to\fB$LOAD_PATH\fR\. Defaults to \fB[\'lib\']\fR\.
.
.IP "\(bu" 4
\fBrequires\fR \- Scripts to require before running tests\.
.
.IP "\(bu" 4
\fBextra\fR \- Extra command line options to append to command\.
.
.IP "" 0
.
.SH "EXAMPLES"
A typical example would look something like:
.
.IP "" 4
.
.nf

minitest:
  tests: spec/*_spec\.rb
  loadpath:
    \- lib
    \- spec
  extra: \'| tapout pretty\'
.
.fi
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright (c) 2010 Thomas Sawyer, Rubyworks
.
.P
Detroit DNote is distributable in accordance with the GPLv3 license\.
.
.SH "SEE ALSO"
dnote(1)
